# Generated by Django 3.2.7 on 2022-11-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exapp', '0002_auto_20221101_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
