# Generated by Django 3.2.7 on 2022-11-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exapp', '0004_alter_course_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='number',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
