# Generated by Django 3.2.7 on 2022-11-08 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exapp', '0004_alter_course_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ChackPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exersise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exapp.exersise')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stdapp.student')),
            ],
        ),
    ]
