# Generated by Django 3.2.7 on 2022-11-08 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exapp', '0004_alter_course_img'),
        ('stdapp', '0002_chackpoint_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChackPoint',
            new_name='CheckPoint',
        ),
    ]
